### ISSUE TITLE
MISSING LOGO - Ninjaone

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapy_peviitor_jobs#2]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/ninjaone/#
browser: Chrome/ FireFox

STEPS TO REPRODUCE:
1)open URL in the browser
2)check the logo

EXPECTED RESULTS:
the logo for Ninjaone should be displayed correctly

ACTUAL RESULTS:
Ninjaone logo is missing

![Screenshot_45](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/124587607/8deaa369-8ba1-44f1-83c3-f8d48b53711e)

**Comment by return1101** [comment]
NinjaOne rezolvat.
