### ISSUE TITLE
Bittnet - Wrong number of available jobs on peviitor.ro

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapy_peviitor_jobs#4]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Bittnet" in the search bar.
3. Click on "Cauta" button
4. Go to the Bittnet company career page: https://www.bittnet.jobs/1048/lista-posturi
5. Check the number of jobs on the peviitor.ro with the number of jobs on the Bittnet site

EXPECTED RESULTS:
The number of jobs displayed on the peviitor.ro website coresponds with the number of jobs displayed on the Bittnet company website.

ACTUAL RESULT:
The number of jobs displayed on the peviitor.ro website does't coresponds with the number of jobs displayed on the Bittnet company website.
[peviitor.ro](https://peviitor.ro/rezultate?q=bittnet&country=Rom%C3%A2nia&page=1) - 1 job
https://www.bittnet.jobs/1048/lista-posturi - 13 jobs

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/b867c391-7193-4788-8b1a-e49549402024)
![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/6852dd77-9a50-4687-9928-652f5fdeb8b6)

**Comment by return1101** [comment]
Rezolvat.
