### ISSUE TITLE
ComplyAdvantage - The job title is incomplete

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapy_peviitor_jobs#5]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "ComplyAdvantage " in the search bar.
3. Click on "Cauta" button
4. Go to the ComplyAdvantage company career page: https://complyadvantage.com/careers/jobs/
5. Check the job title on the peviitor.ro with the job title on the ComplyAdvantage site

EXPECTED RESULTS:
The job title displayed on the peviitor.ro website coresponds with the job title displayed on the ComplyAdvantage company website.

ACTUAL RESULT:
The job title displayed on the peviitor.ro website does't coresponds  with the job title displayed on the ComplyAdvantage company website.
peviitor.ro - Operations Analyst
ComplyAdvantage  - Technology Operations Analyst

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/4763a38c-dc88-4097-8035-caf9181ce02c)

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/40270f67-5f69-44ff-bd57-83ecd718cd90)

**Comment by return1101** [comment]
Rezolvat.
