### ISSUE TITLE
CreativeChaos - Job location is missing

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapy_peviitor_jobs#6]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "CreativeChaos" in the search bar
3. Click on "Cauta" button
4. Go to the CreativeChaoscompany career page: https://apply.workable.com/creativechaos/  and select location: Romania
4. Check the job location on the peviitor.ro with the job location on the CreativeChaos site

EXPECTED RESULT:
Jobs have their location displayed on peviitor.ro.

ACTUAL RESULT:
Jobs have no location displayed on peviitor.ro.

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/0fd770f2-c202-4ff2-bbf2-69e9e0a7bfef)

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/41b6870d-ceb9-4638-a396-626f56fe3ebf)

**Comment by return1101** [comment]
Rezolvat.
