### ISSUE TITLE
FortisGames- Wrong number of available jobs on peviitor.ro

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapy_peviitor_jobs#7]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "FortisGames" in the search bar.
3. Click on "Cauta" button
4. Go to the FortisGamescompany career page: https://www.fortisgames.com/careers/#openings
5. Select location: Remote-Romania
6. Check the number of jobs on the peviitor.ro with the number of jobs on the FortisGamessite

EXPECTED RESULTS:
The number of jobs displayed on the peviitor.ro website coresponds with the number of jobs displayed on the FortisGames company website.

ACTUAL RESULT:
The number of jobs displayed on the peviitor.ro website does't coresponds with the number of jobs displayed on the FortisGames company website.
peviitor.ro - 9 job
FortisGames - 10 jobs

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/540cbe9a-e8ed-4bc9-a389-b859ccbaeb15)

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/e6cc15de-4d68-4169-9762-0606073a9cd4)

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/1f58b8b0-7f5c-452a-ad41-cc41e8a55906)

**Comment by return1101** [comment]
Rezolvat.
