### ISSUE TITLE
FortisGames- Job location is missing

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapy_peviitor_jobs#8]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "FortisGames" in the search bar
3. Click on "Cauta" button
4. Go to the FortisGames career page: https://www.fortisgames.com/careers/#openings
5. Select location: Remote-Romania
6. Check the job location on the peviitor.ro with the job location on the FortisGames site

EXPECTED RESULT:
Jobs have their location displayed on peviitor.ro.

ACTUAL RESULT:
Jobs have no location displayed on peviitor.ro.

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/bf680170-8272-40f6-ba17-848b03255579)

![image](https://github.com/peviitor-ro/Scrapy_peviitor_jobs/assets/143128512/476d32e5-3594-4584-baa8-f7ce014f097c)

**Comment by return1101** [comment]
Rezolvat.
